### ISSUE TITLE
Bootstrap tabs interfere custom menu

### ISSUE THREAD

**Issue by tschortsch22** [moodleuulm/moodle-filter_tabs#4]
Hi!

Bootstrap filter tabs do interfere the functionality of custom menus in Moodle 2.8 using the core "more" theme (no other themes installed). After enabling the boostrap tabs setting the submenu of a custom menu does not show up properly, e.g., submenu 1 is shown when clicking custom menu 2, submenu 2 is shown when clicking any other toplevel menu etc.

With standard filter YUI tabs (bootstrap tabs disabled) everything is fine albeit the nice bootstrap look is lacking.

Kind regards,
George

**Comment by abias** [comment]
Hi George,

thanks for reporting this problem. I could reproduce the phenomenon, it should be fixed now in the latest version of the plugin.

Thanks,
Alex
